public class authNetReq_Wrapper
{
public string ordername {get;set;} 
public string ccnum {get;set;} 
public string ccexp {get;set;} 
public string ccsec {get;set;} 
public string amt {get;set;} 
public string firstname {get;set;} 
public string lastname {get;set;} 
public string billstreet {get;set;} 
public string billcity {get;set;} 
public string billstate {get;set;} 
public string billzip {get;set;} 
public string transid {get;set;} 
public string routingnumber {get;set;} 
public string accountnumber {get;set;} 
public string bankaccounttype {get;set;} 
public string bankname {get;set;} 
public string bankaccountname {get;set;} 
public authNetReq_Wrapper()
{   
}
}